CREATE TABLE BANK_ACCOUNT (
    ACCOUNT_ID NVARCHAR2,
    HOLDER_NAME NVARCHAR2,
    AMOUNT NUMBER(10, 5),
    PRIMARY KEY (ACCOUNT_ID),
    UNIQUE (HOLDER_NAME)
--     CHECK (AMOUNT >= 0)
);

INSERT INTO BANK_ACCOUNT VALUES ('1', 'Sina Karimi', 5000.0);
INSERT INTO BANK_ACCOUNT VALUES ('2', 'Mohammad Nasiri', 4000.0);